import Head from "next/head";
import styles from "../styles/Index.module.css";
import Login from "../compontent/Login";
import axios from "axios";

axios.defaults.baseURL = "http://localhost:8888";
export default function Index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Login />
      </main>

      <footer className={styles.footer}>
        <a href="#" target="_blank" rel="noopener noreferrer">
          联系方式
        </a>
      </footer>
    </div>
  );
}
